food/urls.py
from django.urls import path

from . import views

app_name = "food"
urlpatterns = [
    path('', views.IndexClassView.as_view(), name="index"),
    path('item/', views.item, name="item"),
    path('<int:pk>/', views.FoodDetailView.as_view(), name="detail"),
    path("add", views.CreateItem.as_view(), name ="add"),
    path("update/<int:item_id>", views.update_item, name ="update"),
    path("delete/<int:item_id>", views.delete_item, name ="delete"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.views import register as user_register_view, profilepage
from django.contrib.auth import views as authentication_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include("food.urls")),
    path('register/', user_register_view, name="register"),
    path('profile/', profilepage, name="profile"),
    path('login/', authentication_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    def __str__(self):
        return f"{self.item_name}"

    item_name = models.CharField(max_length=100)
    item_description = models.CharField(max_length=100)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500,
        default="https://static.vecteezy.com/system/resources/previews/016/916/479/original/placeholder-icon-design-free-vector.jpg"
    )
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import  User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.jpg", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user.username}"

food/forms.py
from django import forms

from food.models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            "item_name",
            "item_price",
            "item_description",
            "item_image"
        ]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import  UserCreationForm



class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

food/views.py
from typing import List

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.views.generic import ListView, DetailView, CreateView

from .forms import ItemForm
from .models import Item


# Create your views here
def index(request):
    item_list: List[Item] = Item.objects.all()
    template = loader.get_template("food/index.html")
    context = {
        "item_list": item_list,
    }
    return render(
        request=request,
        template_name="food/index.html",
        context=context
    )

class FoodDetailView(DetailView):
    model = Item
    template_name = "food/detail.html"

class IndexClassView(ListView):
    model = Item
    template_name = "food/index.html"
    context_object_name = "item_list"

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', "item_description", "item_price", "item_image"]
    template_name = "food/item-form.html"

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def item(request):
    return HttpResponse("<h1>This is an item view</h1>")


def detail(request, item_id: int):
    item = Item.objects.get(pk=item_id)
    context = {
        "item": item
    }
    return render(
        request=request,
        template_name="food/detail.html",
        context=context
    )


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("food:index")

    context = {
        "form": form
    }
    return render(
        request=request,
        template_name='food/item-form.html',
        context=context
    )


def update_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect("food:index")
    context = {
        "form": form
    }
    return render(
        request,
        "food/item-form.html",
        context=context
    )


def delete_item(request, item_id: int):
    item = Item.objects.get(pk=item_id)

    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    context = {
        "item": item
    }
    return render(
        request,
        "food/item-delete.html",
        context

    )

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

from users.forms import RegisterForm


# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Welcome {username}, your account has been created")
            return redirect("login")
    else:
        form = RegisterForm()
    return render(
        request=request,
        template_name="users/register.html",
        context={"form": form}
    )
@login_required
def profilepage(request):
    return  render(request, "users/profile.html")

food/templates/food/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Food App, Hello {{ user.username }}</a>
    <div class="navbar">
        <a class="nav-item" href="#">Add item</a>
        <a class="nav-item" href="#">Delete item</a>
        <a class="nav-item" href="#">Menu item</a>
        {{% if user.is_authenticated %}
        	<a href="{% url 'logout' %}">Logout</a>
        	<a href="{% url 'profile' %}">Profile</a>
        {% else %}
        	<a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</nav>
{% if messages %}
	{% for message in messages %}
		<div class="alert alert-{{ message.tags }}">
        {{ message }}
        </div>
	{% endfor %}
{% endif %}
{% block body %}

{% endblock %}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
    <div>
        <img src="{{ object.item_image }}" alt="" width="100px">
        {{ object.item_name }}
        {{ object.item_description }}
        {{ object.item_price }}
    </div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
    <div>
    <a href="{% url 'food:add' %}">Thêm mới</a>
    </div>
    <table border>
        <thead>
        <tr>
            <th>Id</th>
            <th>Image</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Author</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for item in item_list %}
            <tr>
                <td>{{ item.id }}</td>
                <td>
                    <div>
                        <img class="card" alt="" width="100"  src="{{ item.item_image }}">
                    </div>
                </td>
                <td>{{ item.item_name }}</td>
                <td>{{ item.item_description }}</td>
                <td>{{ item.item_price }}</td>
                <td>{{ item.user_name }}</td>
                <td>
                    <div>
                        <a href="{% url 'food:detail' item.id %}">Chi tiết</a>
                        <a href="{% url 'food:update' item.id %}">Cập nhật</a>
                        <a href="{% url 'food:delete' item.id %}">Xóa</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h1>Có muốn xóa {{ item.item_name }} ? </h1>
    <button type="submit">Xác nhận</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

users/templates/users/login.html
{% extends "food/base.html" %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header bg-info">
                        <div class="card-title">Login</div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group mt-2">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="mt-2">Đăng nhập</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/logout.html
<h1>You has been logout</h1>

users/templates/users/profile.html
{{ user.username }}
<p>ssss</p>
{{ user.profile.image.url }}ss
<img alt="" src="{{ user.profile.image.url }}" />

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Đăng ký</button>
</form>